version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: feedback-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    restart: always

  mongodb:
    image: mongo
    container_name: feedback-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    restart: always

volumes:
  mongodb_data:


